name:         h2hpw
version:      "0.0.0.0"
synopsis:     Collider studies on the heavy Higgs boson in the 2HDM
author:       Chan Beom Park
maintainer:   cbpark@gmail.com
license-file: LICENSE
github:       cbpark/h2hpw
category:     Physics

ghc-options:  -Wall -Wcompat -O2 -funbox-strict-fields

dependencies:
  - base >= 4.12.0.0 && < 5
  - bytestring
  - pipes
  - pipes-bytestring
  - zlib
  - hep-utilities

executables:
  h2hpw:
    main: h2hpw.hs
    source-dirs: src
